const express = require("express");
const { requireAuth, requireBusiness, requireAdmin } = require("../../middleware/auth");
const c = require("./finance.controller");
const router = express.Router();
router.use(requireAuth, requireBusiness);
router.get("/accounts", c.listAccounts);
router.post("/accounts", requireAdmin, c.createAccount);
router.patch("/accounts/:id", requireAdmin, c.updateAccount);
router.delete("/accounts/:id", requireAdmin, c.deleteAccount);
router.get("/transactions", c.listTransactions);
router.post("/transactions", requireAdmin, c.createTransaction);
router.get("/expenses", c.listExpenses);
router.post("/expenses", requireAdmin, c.createExpense);
router.patch("/expenses/:id", requireAdmin, c.updateExpense);
router.delete("/expenses/:id", requireAdmin, c.deleteExpense);
router.get("/payments", c.listPayments);
router.post("/payments", requireAdmin, c.createPayment);
router.get("/daily-closings", c.getDailyClosing);
router.post("/daily-closings/close", requireAdmin, c.closeDaily);
router.post("/daily-closings/reopen", requireAdmin, c.reopenDaily);
router.get("/reports/summary", c.reportSummary);
module.exports = { financeRouter: router };
